version: '3.8'
services:
  mysql:
    image: mysql:8.0.34
    restart: always
    ports:
      - '3306:3306'
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass

  postgresql:
    image: postgres:13-alpine
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=pass

  nodejs:
    image: node:16
    container_name: gate_simulator
    working_dir: /app
    volumes:
      - ./gate-simulator:/app
    ports:
      - "9999:9999"
    command: npm start